wandb:
  project: End_to_End_navigation
  name: 5090_quadcopter_obstacles_teacher
  entity: weimmmm-university-of-electronic-science-and-technology-
  mode: online
  run_id:

evaluation:
  enabled: true
  interval: 500
  steps: 1500
  eval_at_start: true
